
package proxies;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonSvc", targetNamespace = "http://service.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonSvc {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.com/PersonSvc/addPersonRequest", output = "http://service.com/PersonSvc/addPersonResponse")
    public boolean addPerson(
        @WebParam(name = "arg0", partName = "arg0")
        PersonS arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.com/PersonSvc/deletePersonRequest", output = "http://service.com/PersonSvc/deletePersonResponse")
    public boolean deletePerson(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns proxies.PersonSArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.com/PersonSvc/getAllPersonsRequest", output = "http://service.com/PersonSvc/getAllPersonsResponse")
    public PersonSArray getAllPersons();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxies.PersonS
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.com/PersonSvc/getPersonRequest", output = "http://service.com/PersonSvc/getPersonResponse")
    public PersonS getPerson(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
